#!/bin/sh
set -e
package_name=xdg-user-dirs-fix
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/xdg-user-dir"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/xdg-user-dir"
;;
esac
exit 0
